---
layout: null
published: true
title: Assert
abstract: The assert module provides functions that throw AssertionErrors when particular conditions are not met.
author: Bediako George, Serena Lei
categories: api
---

Assert functions evaluate predicates and can help developers locate problems in their code, aiding the debugging process.  All assertion methods provide both the actual and expected values to the assertion error for display purposes. Airlift's many unit tests make extensive use of this module. The assert module can be found on [CommonJS](http://wiki.commonjs.org/wiki/Unit_Testing/1.0).


     var assert = require('airlift/assert');     


<p id="Assert_fail"></p>
### fail(Object actual, Object expected, String message, String operator, String stackStartFunction)
#### Return type:  n/A

<p> <label class="new">Added in 2.0</label>
Description under construction.
</p>


     assert.fail(true, false, 'false positive', '===', assert.eq);
     THROWS: assert.AssertionError;


<p id="Assert_ok"></p>
### ok(Object value, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests whether 'value' is truthy.
</p>


     exports['test example'] = function(asserts)
     {
          assert.ok(1, 'result is not truthy');
     }

     STDOUT: OK ... test example

     exports['test example'] = function(asserts)
     {
          assert.ok(0, 'result is not truthy');
     }

     STDOUT:      result is not truthy true == 0
             Failed ... test example


<p id="Assert_eq"></p>
### eq(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests shallow, coercive equality with ==.
</p>


     exports['test example'] = function(asserts)
     {
          var result = 1;
          assert.eq(result, 'one', 'function failed to convert integer
               to written numbers');
     }

     STDOUT: OK ... test example

     exports['test example'] = function(asserts)
     {
          var result = 1;
          assert.eq(result, 'one', 'integer not converted to written numbers');
     }

     STDOUT:      integer not converted to written numbers ! == 1
             Failed ... test asserts


<p id="Assert_notEq"></p>
### notEq(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests for whether two objects are not equal with != .
</p>


     exports['test example'] = function(asserts)
     {
          var result = 2 + 2;
          assert.eq(result, 5, 'oh no, we've lapsed into an Orwellian society');
     }

     STDOUT OK ... test example


<p id="Assert_deepEqual"></p>
### deepEqual(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests a deep equality relation.
</p>


     exports['test example'] = function(asserts)
     {
          var a = [1, 2, 3];
          var b = [1, 2, 3];
          assert.deepEqual(b, a, 'elements of two matrices were not equal.');
     }

     STDOUT OK ... test example


<p id="Assert_notDeepEqual"></p>
### notDeepEqual(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests for any deep inequality.
</p>


     exports['test example'] = function(asserts)
     {
          var a = [1, 2, 3];
          var b = [1, 2, 4];
          assert.notDeepEqual(b, a, 'differing elements of two matrices were equal.');
     }

     STDOUT OK ... test example



<p id="Assert_kindaEqual"></p>
### kindaEqual(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="unstable">Added in 2.0</label>
Tests equality, as determined by ==.
</p>


     exports['test example'] = function(asserts)
     {
          var result = 1;
          assert.kindaEqual(result, 'one', 'result is incorrect');
     }

     STDOUT: OK ... test example

<p id="Assert_notKindaEqual"></p>
### notKindaEqual(Object actual, Object expected, String message)
#### Return type: n/A

<p> <label class="unstable">Added in 2.0</label>
Tests for inequality, as determined by != .
</p>


     exports['test example'] = function(asserts)
     {
          var result = 'luma';
          assert.notKindaEqual(result, null, 'error: needs more starbits');
     }

     STDOUT: OK ... test example


<p id="Assert_throws"></p>
### throws(Object block, Object error, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests that 'block' throws an error as expected. 'error' and 'message' are optional. 'error' can be constructor, regexp or validation function.
</p>


     exports['test example'] = function(asserts)
     {
          list = util.list();
          assert.throws(function()
               {
                    util.multiTry(function(_tries, _exception)
                         {
                              list.add('stuff');
                              if (_tries < 6) throw 'error';
                          }, 5);
               },'multi try should throw an exception');
     }

     STDOUT OK ... test example



<p id="Assert_doesNotThrow"></p>
### doesNotThrow(Object block, Object error, String message)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Tests that 'block' does not throw an error. 'error' and 'message' are optional. 'error' can be constructor, regexp or validation function.
</p>


     exports['test example'] = function(asserts)
     {
          list = util.list();
          assert.doesNotThrows(function()
               {
                    util.multiTry(function(_tries, _exception)
                         {
                              list.add('stuff');
                              if (_tries < 6) throw 'error';
                          }, 7);
               },'multi try should not throw an exception');
     }

     STDOUT OK ... test example


<p id="Assert_ifError"></p>
### ifError(Object value)
#### Return type: n/A

<p> <label class="new">Added in 2.0</label>
Evaluates 'value' to a boolean using the abstract method Toboolean and throws 'value' if it is true. Useful when testing the first argument, error in callbacks.
</p>


     try {
          throw 'this is an error';
     }
     catch (e) {
          assert.ifError(e);
     }








